language: python

sudo: required
dist: trusty

python:
  - "2.7"

branches:
  only:
    - master

install:
  - wget https://github.com/MachineLearningControl/OpenMLC-Python/releases/download/v0.0.4/mlc-python-ubuntu-14.04_0.0.4_amd64.deb
  - sudo dpkg -i mlc-python-ubuntu-14.04_0.0.4_amd64.deb

script:
  - cd tests
  - ./run_unit_tests.sh
